import Foundation

public struct ExecutionSource: Sendable, Hashable, Identifiable {
    public var port: UInt16
    public var name: String
    public var id: UInt16 { port }
    public init(port: UInt16, name: String) { self.port = port; self.name = name }
}

public struct ExecutionEvent: Decodable, Sendable, Identifiable {
    public var id: Int
    public var kind: String
    public var text: String
    public var time: Double
    public var updated: Double
    public var choice: Int
}

public struct ExecutionTrace: Decodable, Sendable, Identifiable {
    public var id: String
    public var parentId: String?
    public var endpoint: String
    public var started: Double
    public var ended: Double?
    public var status: String
    public var model: String
    public var thinking: Bool?
    public var stream: Bool
    public var input: String?
    public var events: [ExecutionEvent]?
    public var truncated: Bool
    public var finishReason: String?
    public var outputTokens: Int
    public var preview: String
    public var usage: [String: Int]?
    public var isRunning: Bool { status == "running" }
}

public struct ExecutionSnapshot: Decodable, Sendable {
    public var executions: [ExecutionTrace]
    public var capacity: Int
    public var textLimit: Int
    public var dropped: Int
}

public final class ExecutionClient: @unchecked Sendable {
    private let session: URLSession
    public init() {
        let config = URLSessionConfiguration.ephemeral
        config.timeoutIntervalForRequest = 2
        config.urlCache = nil
        session = URLSession(configuration: config)
    }
    private func request(port: UInt16, path: String, method: String = "GET") async throws -> Data {
        var request = URLRequest(url: URL(string: "http://127.0.0.1:\(port)\(path)")!)
        request.httpMethod = method
        let (data, response) = try await session.data(for: request)
        guard let response = response as? HTTPURLResponse, response.statusCode == 200 else {
            throw URLError(.badServerResponse)
        }
        return data
    }
    private func decode<T: Decodable>(_ type: T.Type, _ data: Data) throws -> T {
        let decoder = JSONDecoder()
        decoder.keyDecodingStrategy = .convertFromSnakeCase
        return try decoder.decode(type, from: data)
    }
    public func list(port: UInt16) async throws -> ExecutionSnapshot {
        try decode(ExecutionSnapshot.self, await request(port: port, path: "/executions"))
    }
    public func detail(port: UInt16, id: String) async throws -> ExecutionTrace {
        // IDs are generated by Dyno, never a user-supplied URL or host.
        guard id.allSatisfy({ $0.isHexDigit }) else { throw URLError(.badURL) }
        return try decode(ExecutionTrace.self, await request(port: port, path: "/executions/\(id)"))
    }
    public func clear(port: UInt16) async throws {
        _ = try await request(port: port, path: "/executions", method: "DELETE")
    }
}
